files: backend
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: python
        types: [python]
        entry: black

      - id: ruff
        name: ruff
        language: python
        types: [python]
        entry: ruff


        